config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/search', to: 'search#index'
  get '/app', to: 'app#index'
  get '/app/update', to: 'app#update'
  get '/ranking', to: 'static_pages#ranking'
  get '/recent', to: 'static_pages#recent'
  get '/category', to: 'static_pages#category'
  root "static_pages#home"

  resources :users, :only => [:show]

  namespace :admin do
  	root "users#index"
  	resources :applications
  	resources :categories
  	resources :users, only: [:index, :show]
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
		@results = Application.app_search(params[:search],params[:category])
		@applications = []
		@results.each do |result|
			if result.average_rating.to_i >= params[:minrating].to_i
				@applications << result
			end
		end
		if @applications.present?
			@applications = @applications.paginate(page: params[:page_app], :per_page => 16)
		end	
		@search = params[:search]
		@minrating = params[:minrating]
		@categories = Category.all
		@category = params[:category]
    end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<!-- page content -->
  <div class="main-wrapper">
    <div class="search-input-page">
          <div style="width: 800px; margin: 0px auto; padding-top: 30px;">
              <form action="<%= search_path %>" method="get">
                  <div class="row">
                      <div class="form-group col-sm-10" style="margin-bottom: 0;">
                          <input type="text" class="form-control" id="search" name="search" value="<%= @search %>" placeholder="applications, ...">
                      </div>
                      <div class="col-sm-2">
                          <button type="submit" class="btn btn-success" style="">Search</button>
                      </div>
                      <div class="form-group col-sm-4" style="margin-top: 15px;">
                          <label for="category">Category:</label>
                          <select class="form-control" id="category" name="category">
                              <option value='all'  selected>All</option>
                              <% @categories.each do |category| %>
                                <option value="<%= category.category_name %>"><%= category.category_name %></option>
                              <% end %>  
                          </select>
                      </div>
                      <div class="col-sm-4" style="margin-top: 15px;">
                          <label for="range">Minimum Rate:</label>
                          <div class="range range-success" style="margin-top: 5px; background-color: white;">
                              <input type="range" name="minrating" min="0" max="5" value="<%= @minrating %>" onchange="$('#rate-output').text(value+'*'); alert(value);">
                              <output id="rate-output"><%= @minrating %> *</output>
                          </div>
                      </div>
                  </div>    
              </form>
          </div>
      </div>
      <section class="content aa_clearfix">
          <div class="show-app container-resp aa_grid aa_grid--2-m aa_grid--3-l aa_grid--4-xl aa_padding-t--20" style="margin-top: 20px;">
              <!-- app reviews -->
              <% if @applications.present? %>
                <% @applications.each do |application| %>
                    <div class="aa_grid__elem">
                        <a href="<%= app_path %>?id=<%= application.id %>" class="aa_ar aa_clearfix item">
                            <div class="aa_ar__score">
                                <div class="aa_app__score" data-score="<%= application.average_rating %>">
                                    <svg class="aa_app__score__svg" height="100" width="100" stroke-dashoffset="<%= 250 - application.average_rating * 50 %>">
                                        <circle class="aa_app__score__svg__bg" cx="50" cy="50" r="40"></circle>
                                        <circle class="aa_app__score__svg__line" cx="50" cy="50" r="40"></circle>
                                    </svg>
                                </div>
                            </div>
    
                            <div class="aa_ar__icon">
                                <div class="aa_app__icon aa_bg aa_grad--5">
                                    <div class="aa_bg__ aa_bg__--abs aa_wait-to-load js-wait-to-load loaded" style="background-image: url('<%= application.appimage %>')"></div>
                                </div>
                            </div>
    
                            <div class="aa_ar__text">
                                <div class="aa_ar__text__">
                                    <h3 class="aa_ar__text__title aa_text--truncate">
                                        <%= application.application_name %>
                                    </h3>
    
                                    <div class="aa_ar__text__developer aa_text--truncate">
                                        <% application.categories.each do |category| %>
                                            <%= category.category_name %>,
                                        <% end %>   
                                    </div>
                                </div>
                            </div>
    
                            <div class="aa_ar__details"><%= raw(application.description) %></div>
                        </a>
                    </div>
                  <% end %>
              <% else %>
                <h3>Sorry, no results found!</h3>
              <% end %>
  
                  <!-- app reviews end -->
          </div>
          <% if @applications.present? %>
            <div class="paginate-app" style="margin-left: 500px;">
                <%= will_paginate @applications, :param_name => 'page_app' %>
            </div>
          <% end %>  
      </section>
  
  </div>
  <!-- page content end -->