config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/search', to: 'search#index'
  get '/app', to: 'app#index'
  get '/app/update', to: 'app#update'
  get '/ranking', to: 'static_pages#ranking'
  get '/recent', to: 'static_pages#recent'
  get '/category', to: 'static_pages#category'
  root "static_pages#home"

  resources :users, :only => [:show]

  namespace :admin do
  	root "users#index"
  	resources :applications
  	resources :categories
  	resources :users, only: [:index, :show]
  end
end

app/models/application.rb
class Application < ApplicationRecord
	has_many :reviews
	has_many :company_applications
	has_many :application_categories
  has_many :categories, :through => :application_categories
  mount_uploader :appimage, AppimageUploader
  mount_uploader :screen1, Screen1Uploader
  mount_uploader :screen2, Screen2Uploader
  mount_uploader :screen3, Screen3Uploader
  mount_uploader :screen4, Screen4Uploader
  mount_uploader :screen5, Screen5Uploader



	
	def self.app_search(search,category = 'all')
    if search
      if category == 'all'
        self
          .select("applications.*,companies.company_name")
          .left_outer_joins(company_applications: :company)
          .left_outer_joins(application_categories: :category)
          .where('application_name LIKE ? OR applications.description LIKE ?', "%#{search}%", "%#{search}%")
          .order("applications.created_at DESC")
          .group("applications.id")
      else
        self
          .select("applications.*,companies.company_name")
          .left_outer_joins(company_applications: :company)
          .left_outer_joins(application_categories: :category)
          .where('application_name LIKE ? OR applications.description LIKE ?', "%#{search}%", "%#{search}%")
          .where('category_name = ?', category)
          .order("applications.created_at DESC")
          .group("applications.id")
      end    
    else
      self
          .select("applications.*,companies.company_name")
          .left_outer_joins(company_applications: :company)
          .order("applications.created_at DESC")
    end
  end

  def self.app_show(id)
    self
      .select("applications.*,companies.company_name")
      .left_outer_joins(company_applications: :company)
      .left_outer_joins(application_categories: :category)
      .where('applications.id LIKE ?', id)
      .group("applications.id")
  end
  
  def average_rating
    if self.reviews.size > 0
        self.reviews.average(:star).round(1)
    else
        0
    end 
  end
  
  def rating_count(star)
    self.reviews.where(star: star).size
  end
  
  def rating_percent(star)
    if self.reviews.size > 0
      self.reviews.where(star: star).size * 100 / self.reviews.size 
    else 
      0
    end  
  end
  
end

app/controllers/admin/applications_controller.rb
class Admin::ApplicationsController < ApplicationController
	before_action :authenticate_user!, :verify_admin
	before_action :find_app, except: [:index, :new, :create]
	def index
		if params[:application_hint].nil?
			@applications = Application.paginate(page: params[:page], :per_page => 11)
		else
			@applications = Application.where("application_name LIKE :name", name: "%#{params[:application_hint]}%")
							.paginate(page: params[:page], :per_page => 11)
		end
	end

	def new
		@application = Application.new
		@categories = Category.all
	end

	def create
		@application = Application.new application_params
		if @application.save
			if params[:category_ids].present?
				params[:category_ids].each do |id|
					category = Category.find_by id: id
					unless category.nil? || @application.categories.include?(category)
						@application.categories << category
					end
				end
			end
			flash[:success] = "Application created"
			redirect_to admin_applications_path
		else
			load_categories
			render :new
		end
	end

	def edit
		@categories = Category.all
	end

	def update
		if @application.update application_params
			params[:application][:category_ids].each do |id|
				category = Category.find_by id: id
				unless category.nil? || @application.categories.include?(category)
					@application.categories << category
				end
			end
			flash[:success] = "Application Updated"
			redirect_to admin_application_path
		else
			load_categories
			render :edit
		end
	end

	def show
	end

	def destroy
		@application.destroy
		flash[:success] = "App deleted!"
		redirect_to admin_applications_path
	end

	private
	def find_app
		@application = Application.find_by id: params[:id]
		if @application.nil?
			flash.now[:danger] = "Can't display app information"
			redirect_to root_path
		end
	end
	
	def application_params
    	params.require(:application).permit :application_name, :description, :appimage, :screen1, :screen2, :screen3, 
    	:screen4, :screen5, :device, :team
	end

	def categories_params
		params.require(:application).permit category_ids: []
	end

	def load_categories
		@categories = Category.all
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  include SessionsHelper

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up do |user_params|
      user_params.permit :email, :password, :password_confirmation,
        :avatar, :avatar_cache
    end
    devise_parameter_sanitizer.permit :account_update do |user_params|
      user_params.permit :email, :password, :password_confirmation,
        :current_password, :avatar, :avatar_cache, :remove_avatar
    end
  end

end

app/helpers/admin/applications_helper.rb
module Admin::ApplicationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/applications/_app_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @application] do |f| %>
      <%= render "admin/shared/error_messages", object: @application %>

      <%= f.label :application_name %>
      <%= f.text_field :application_name, class: "form-control" %>

      <%= f.label :device %>
      <%= f.text_field :device, class: "form-control" %>

      <%= f.label :team %>
      <%= f.text_field :team, class: "form-control" %>

      <%= f.label :description %>
      <%= f.text_area :description, class: "ckeditor" %>

      <div class="field">
         <%= f.label :appimage %>
         <p>
           <%= image_tag(@application.appimage.url, :width => 100, :height => 100) if @application.appimage? %>
         </p>
         <%= f.file_field :appimage, class: "form-control" %>
         <%= f.hidden_field :appimage_cache %>

         <%= f.label :screen1 %>
         <p>
           <%= image_tag(@application.screen1.url, :width => 100, :height => 100) if @application.screen1? %>
         </p>
         <%= f.file_field :screen1, class: "form-control" %>
         <%= f.hidden_field :screen1_cache %>

         <%= f.label :screen2 %>
         <p>
           <%= image_tag(@application.screen2.url, :width => 100, :height => 100) if @application.screen2? %>
         </p>
         <%= f.file_field :screen2, class: "form-control" %>
         <%= f.hidden_field :screen2_cache %>


         <%= f.label :screen3 %>
         <p>
           <%= image_tag(@application.screen3.url, :width => 100, :height => 100) if @application.screen3? %>
         </p>
         <%= f.file_field :screen3, class: "form-control" %>
         <%= f.hidden_field :screen3_cache %>


         <%= f.label :screen4 %>
         <p>
           <%= image_tag(@application.screen4.url, :width => 100, :height => 100) if @application.screen4? %>
         </p>
         <%= f.file_field :screen4, class: "form-control" %>
         <%= f.hidden_field :screen4_cache %>


         <%= f.label :screen5 %>
         <p>
           <%= image_tag(@application.screen5.url, :width => 100, :height => 100) if @application.screen5? %>
         </p>
         <%= f.file_field :screen5, class: "form-control" %>
         <%= f.hidden_field :screen5_cache %>


         
      </div>
      <br>

      <%= select_tag :category_ids, 
      options_from_collection_for_select(@categories, "id", "category_name"), 
      { class: "form-control input-sm selectpicker" , :multiple => true, :size => 4} %>
      <br>
      <p> 
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>
</div>
  

app/views/admin/applications/edit.html.erb
<div class="page-content">
   	<div class="row">
		<%= render "admin/shared/wrap" %>	  
		<h1>Edit Application</h1>
		<%= render "app_form" %>
	</div>
</div>

app/views/admin/applications/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App Review</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="css/styles.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="page-content">
    	<div class="row">
		    <%= render "admin/shared/wrap" %>
			<div class="col-md-10">
				<div class="content-box-large">
					<div class="panel-heading">
						<div class="panel-title">Application List</div>
					</div>
					<div class="panel-body">
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
							<thead>
								<tr>
									<th>Application Name</th>
									<th>Description</th>
									<th>Creating date</th>
									<th>Updating at</th>
									<th>Number Of Categories</th>
								</tr>
							</thead>
							<tbody>
								<% @applications.each do |application|%>
									<tr class="gradeU">
										<td><%= link_to application.application_name, admin_application_path(application) %></td>
										<td><%= raw(application.description) %></td>
										<td><%= application.created_at %></td>
										<td><%= application.updated_at %></td>
										<td><%= application.categories.count %></td>
									</tr>
								<% end %>
							</tbody>
						</table>
						<%= will_paginate %>
					</div>
				</div>
	  		</div>
  		</div>
	</div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="bootstrap/js/bootstrap.min.js"></script>
    <script src="js/custom.js"></script>
  </body>
</html>

app/views/admin/applications/new.html.erb
<div class="page-content">
    <div class="row">
		<%= render "admin/shared/wrap" %>
	 	<h1>New Application</h1>
		<%= render "app_form" %>
	</div>

</div>

app/views/admin/applications/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App Review</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="css/styles.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="page-content">
    	<div class="row">
		    <%= render "admin/shared/wrap" %>
	  		<div class="col-md-6">
	  			<div class="content-box-large">
	  				<div class="panel-heading">
						<div class="panel-title"><%= @application.application_name %></div>
            <%= image_tag(@application.appimage.url, :width => 100, :height => 100) if @application.appimage? %>
						
						<div class="panel-options">
							<a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
							<a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
						</div>
					</div>
	  				<div class="panel-body">
              <div class="panel-body">
                <%= raw(@application.description) %>
              </div>
              <div class="panel-body">
                <%= @application.team %>
              </div>
              <div class="panel-body">
                <%= @application.device %>
              </div>
              <p>
                <%= link_to "Delete", admin_application_path, method: :delete, data: { confirm: "You sure?"}, class: "btn btn-danger" %>
              </p>
              <p>
                <%= link_to "Edit", edit_admin_application_path, class: "btn btn-success" %>
              </p>
              
	  				</div>
            <div class="panel-body">
              <p>
                <h6>Categories</h6>
                <% @application.categories.each do |category| %>
                  <%= link_to category.category_name,  admin_category_path(category) %>
                <% end %>
              </p>
            </div>
	  			</div>
	  		</div>
  		</div>
	</div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="bootstrap/js/bootstrap.min.js"></script>
    <script src="js/custom.js"></script>
  </body>
</html>