config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/search', to: 'search#index'
  get '/app', to: 'app#index'
  get '/app/update', to: 'app#update'
  get '/ranking', to: 'static_pages#ranking'
  get '/recent', to: 'static_pages#recent'
  get '/category', to: 'static_pages#category'
  root "static_pages#home"

  resources :users, :only => [:show]

  namespace :admin do
  	root "users#index"
  	resources :applications
  	resources :categories
  	resources :users, only: [:index, :show]
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  has_many :likes
  mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  validates_integrity_of :avatar
  validates_processing_of :avatar
         
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      #user.name = auth.info.name   # assuming the user model has a name
      #user.image = auth.info.image # assuming the user model has an image
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
  
  def self.user_search(search)
    if search
      self.where('email LIKE ?', "%#{search}%")
    else
      self.all
    end
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
	before_action :authenticate_user!, :verify_admin
	before_action :find_user, only: :show
	def index
		@users = User.paginate(page: params[:page], :per_page => 11)
	end

	def show
	end

	private
	def find_user
		@user = User.find_by id: params[:id]
		if @user.nil?
			flash.now[:danger] = "Can't display user information"
			redirect_to root_path
		end
	end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
		@reviews = current_user.reviews
	end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App Review</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="css/styles.css" rel="stylesheet">
  </head>
  <body>

    <div class="page-content">
    	<div class="row">
		    <%= render "admin/shared/wrap" %>
			<div class="col-md-10">
				<div class="content-box-large">
					<div class="panel-heading">
						<div class="panel-title">Categories List</div>
					</div>
					<div class="panel-body">
						<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="example">
							<thead>
								<tr>
									<th>User Email</th>
									<th>Sign in count</th>
									<th>Current Sign in</th>
									<th>Last Sign in</th>
								</tr>
							</thead>
							<tbody>
								<% @users.each do |user|%>
									<tr class="gradeU">
										<td><%= link_to user.email,  admin_user_path(user) %></td>
										<td><%= user.sign_in_count %></td>
										<td><%= user.current_sign_in_at %></td>
										<td><%= user.last_sign_in_at %></tr>
									</tr>
								<% end %>
							</tbody>
						</table>
						<%= will_paginate %>
					</div>
				</div>
	  		</div>
  		</div>
	</div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="bootstrap/js/bootstrap.min.js"></script>
    <script src="js/custom.js"></script>
  </body>
</html>

app/views/admin/users/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App Review</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- styles -->
    <link href="css/styles.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <div class="page-content">
    	<div class="row">
		    <%= render "admin/shared/wrap" %>
	  		<div class="col-md-6">
	  			<div class="content-box-large">
	  				<div class="panel-heading">
						<div class="panel-title"><%= @user.email %></div>
              <%= image_tag(@user.avatar.url, :width => 100, :height => 100) if @user.avatar? %>	
						<div class="panel-options">
							<a href="#" data-rel="collapse"><i class="glyphicon glyphicon-refresh"></i></a>
							<a href="#" data-rel="reload"><i class="glyphicon glyphicon-cog"></i></a>
						</div>
					</div>
	  				<div class="panel-body">
	  				</div>
	  			</div>
	  		</div>
  		</div>
	</div>

  		



    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://code.jquery.com/jquery.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="bootstrap/js/bootstrap.min.js"></script>
    <script src="js/custom.js"></script>
  </body>
</html>