config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get '/search', to: 'search#index'
  get '/app', to: 'app#index'
  get '/app/update', to: 'app#update'
  get '/ranking', to: 'static_pages#ranking'
  get '/recent', to: 'static_pages#recent'
  get '/category', to: 'static_pages#category'
  root "static_pages#home"

  resources :users, :only => [:show]

  namespace :admin do
  	root "users#index"
  	resources :applications
  	resources :categories
  	resources :users, only: [:index, :show]
  end
end

app/views/admin/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "error.contain" %> <%= pluralize object.errors.count, "error" %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_wrap.html.erb
<div class="col-md-2">
    <div class="sidebar content-box" style="display: block; color: blue;">
        <ul class="nav">
            <!-- Main menu -->
            <li class="current"><i class="glyphicon glyphicon-home"></i><%= link_to "Home Page",  root_path %></li>
            <li><i class="glyphicon glyphicon-folder-open"></i><%= link_to "Categories", admin_categories_path %></li>
            <li><i class="glyphicon glyphicon-cloud"></i><%= link_to "Applications", admin_applications_path %></li>
            <li><i class="glyphicon glyphicon-user"></i><%= link_to "Users", admin_users_path %></li>
            <li><i class="glyphicon glyphicon-plus"></i><%= link_to "Add App", new_admin_application_path %></li>
            <li><i class="glyphicon glyphicon-plus"></i><%= link_to "Add Category", new_admin_category_path %></li>
        </ul>
    </div>
</div>